<a href="https://colab.research.google.com/github/vellsant/extensao_analisededados/blob/main/Extens%C3%A3o_AnaliseDeDados_ProjetoFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Projeto final: Análise de resultados de jogos de xadrez entre múltiplos usuários do site Lichess** <br>
A base de dados utilizada pode ser acessada em [Kaggle.com](https://www.kaggle.com/datasets/datasnaek/chess)

In [1]:
#Importando as bibliotecas que serão utilizadas na análise.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Criando um Dataframe com a Base de Dados "games.csv"
games_raw_df = pd.read_csv("/content/games.csv")
display(games_raw_df)

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5
1,l1NXvwaE,True,1.504130e+12,1.504130e+12,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4
2,mIICvQHh,True,1.504130e+12,1.504130e+12,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3
3,kWKvrqYL,True,1.504110e+12,1.504110e+12,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,EfqH7VVH,True,1.499791e+12,1.499791e+12,24,resign,white,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,Dutch Defense,2
20054,WSJDhbPl,True,1.499698e+12,1.499699e+12,82,mate,black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,Queen's Pawn,2
20055,yrAas0Kj,True,1.499698e+12,1.499698e+12,35,mate,white,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,Queen's Pawn Game: Mason Attack,3
20056,b0v4tRyF,True,1.499696e+12,1.499697e+12,109,resign,white,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,Pirc Defense,4
20057,N8G2JHGG,True,1.499643e+12,1.499644e+12,78,mate,black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,Queen's Pawn Game: Mason Attack,3

Nesta seção iremos criar novos Dataframes apenas com os dados que nos interessam para análise, ou seja, excluiremos algumas colunas.

In [3]:
#Visualiza quais são as colunas presentes no Dataframe "games_raw_df" com a função info()
print(games_raw_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20058 non-null  object
 1   rated           20058 non-null  bool
 2   created_at      20058 non-null  float64
 3   last_move_at    20058 non-null  float64
 4   turns           20058 non-null  int64
 5   victory_status  20058 non-null  object
 6   winner          20058 non-null  object
 7   increment_code  20058 non-null  object
 8   white_id        20058 non-null  object
 9   white_rating    20058 non-null  int64
 10  black_id        20058 non-null  object
 11  black_rating    20058 non-null  int64
 12  moves           20058 non-null  object
 13  opening_eco     20058 non-null  object
 14  opening_name    20058 non-null  object
 15  opening_ply     20058 non-null  int64
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 2.3+ MB
None

In [4]:
#Cria um Dataframe contendo apenas as colunas "rated", "victory_status", "winner", "increment_code", "white_rating", "black_rating", "opening_eco", "opening_name" e "opening_ply"
games_treated_df = games_raw_df.drop(labels=['id','created_at','last_move_at','turns','white_id','black_id','moves'], axis=1,inplace=False)
print(games_treated_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rated           20058 non-null  bool
 1   victory_status  20058 non-null  object
 2   winner          20058 non-null  object
 3   increment_code  20058 non-null  object
 4   white_rating    20058 non-null  int64
 5   black_rating    20058 non-null  int64
 6   opening_eco     20058 non-null  object
 7   opening_name    20058 non-null  object
 8   opening_ply     20058 non-null  int64
dtypes: bool(1), int64(3), object(5)
memory usage: 1.2+ MB
None

In [5]:
#Cria um Dataframe apenas com as partidas em que as peças brancas venceram
games_white_win_df = games_treated_df.loc[games_treated_df['winner'] == 'white']
display(games_white_win_df)
print(games_white_win_df.describe())

,rated,victory_status,winner,increment_code,white_rating,black_rating,opening_eco,opening_name,opening_ply
0,False,outoftime,white,15+2,1500,1191,D10,Slav Defense: Exchange Variation,5
2,True,mate,white,5+10,1496,1500,C20,King's Pawn Game: Leonardis Variation,3
3,True,mate,white,20+0,1439,1454,D02,Queen's Pawn Game: Zukertort Variation,3
4,True,mate,white,30+3,1523,1469,C41,Philidor Defense,5
6,True,resign,white,10+0,1520,1423,D00,Blackmar-Diemer Gambit: Pietrowsky Defense,10
...,...,...,...,...,...,...,...,...,...
20050,True,outoftime,white,10+0,1243,1142,A20,English Opening: King's English Variation,2
20052,True,resign,white,10+10,1219,1250,A40,English Defense,4
20053,True,resign,white,10+10,1691,1220,A80,Dutch Defense,2
20055,True,mate,white,10+0,1219,1286,D00,Queen's Pawn Game: Mason Attack,3
20056,True,resign,white,10+0,1360,1227,B07,Pirc Defense,4

       white_rating  black_rating   opening_ply
count  10001.000000  10001.000000  10001.000000
mean    1634.184182   1538.876712      4.862114
std      290.360578    282.227837      2.748142
min      784.000000    795.000000      1.000000
25%     1436.000000   1343.000000      3.000000
50%     1603.000000   1512.000000      4.000000
75%     1822.000000   1728.000000      6.000000
max     2700.000000   2723.000000     28.000000

In [6]:
#Cria um Dataframe apenas com as partidas em que as peças pretas venceram
games_black_win_df = games_treated_df.loc[games_treated_df['winner'] == 'black']
display(games_black_win_df)
print(games_black_win_df.describe())

,rated,victory_status,winner,increment_code,white_rating,black_rating,opening_eco,opening_name,opening_ply
1,True,resign,black,5+10,1322,1261,B00,Nimzowitsch Defense: Kennedy Variation,4
7,False,resign,black,15+30,1413,2108,B00,Nimzowitsch Defense: Kennedy Variation | Link...,5
8,True,resign,black,15+0,1439,1392,C50,Italian Game: Schilling-Kostic Gambit,6
11,False,resign,black,20+60,1381,1867,C02,French Defense: Advance Variation | Paulsen A...,9
12,False,resign,black,5+40,1381,1936,C00,French Defense: Knight Variation,3
...,...,...,...,...,...,...,...,...,...
20041,True,mate,black,10+10,1263,1770,D00,Queen's Pawn Game: Mason Attack,3
20046,True,mate,black,10+10,1250,1235,B07,Pirc Defense,4
20051,True,mate,black,10+10,1237,1231,C00,French Defense: Knight Variation,3
20054,True,mate,black,10+0,1233,1196,A41,Queen's Pawn,2
20057,True,mate,black,10+0,1235,1339,D00,Queen's Pawn Game: Mason Attack,3

       white_rating  black_rating  opening_ply
count   9107.000000   9107.000000  9107.000000
mean    1549.246184   1638.227298     4.742396
std      282.916650    289.835927     2.819476
min      784.000000    789.000000     1.000000
25%     1351.000000   1438.500000     3.000000
50%     1525.000000   1609.000000     4.000000
75%     1741.000000   1828.000000     6.000000
max     2621.000000   2621.000000    28.000000

In [11]:
display(games_white_win_df.groupby(by='opening_name').count())

,rated,victory_status,winner,increment_code,white_rating,black_rating,opening_eco,opening_ply
opening_name,,,,,,,,
Alekhine Defense,23,23,23,23,23,23,23,23
Alekhine Defense #2,1,1,1,1,1,1,1,1
Alekhine Defense: Brooklyn Variation,2,2,2,2,2,2,2,2
Alekhine Defense: Exchange Variation,3,3,3,3,3,3,3,3
Alekhine Defense: Four Pawns Attack,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
Zukertort Opening: Sicilian Invitation,18,18,18,18,18,18,18,18
Zukertort Opening: Slav Invitation,9,9,9,9,9,9,9,9
Zukertort Opening: Tennison Gambit,22,22,22,22,22,22,22,22
Zukertort Opening: The Walrus,1,1,1,1,1,1,1,1
Zukertort Opening: Vos Gambit,1,1,1,1,1,1,1,1